import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { Portal } from '../src/portal.ts';
import { startPortalServer } from '../src/server.ts';
import { serveBrowserService } from '../src/browser-service/service.ts';
import { BrowserServiceClient } from '../src/browser-service/client.ts';
import { generatePortalKey, RpcSocket } from './rpc-client.ts';
import { PORTAL_PAIR_REQUEST_TYPE, paneTargets } from '@weave/product-protocol';
const binary = process.env.CEF_BINARY;
if (!binary) throw new Error('CEF_BINARY required');
const root = await mkdtemp('/tmp/weave-agent-acceptance-');
const node = Bun.which('node')!;
const fixture = Bun.serve({ hostname: '127.0.0.1', port: 0, fetch: request => new Response(new URL(request.url).pathname === '/api' ? 'network-evidence' : '<!doctype html><title>Agent browser acceptance</title><h1>Shared page</h1><button onclick="document.querySelector(\'h1\').textContent=\'Agent clicked\'">Click me</button><script>console.log("agent-console-evidence");fetch("/api");window.ticks=0;setInterval(()=>ticks++,50)</script>', { headers: { 'content-type': new URL(request.url).pathname === '/api' ? 'text/plain' : 'text/html' } }) });
const owner = await serveBrowserService({ stateDirectory: root, binary: '/unused-chrome', cefBinary: resolve(binary) });
const backend = new BrowserServiceClient(root, '/unused-chrome', resolve(binary));
const config = { stateDirectory: root, listen: { hostname: '127.0.0.1', port: 0 }, displayName: 'Browser agent acceptance', allowedOrigins: [], executionContexts: [{ executionContextId: 'context', name: 'Acceptance', path: root }], agents: [{ agentId: 'fixture', name: 'Acceptance agent', command: node, args: [resolve(import.meta.dir, 'browser-agent-fixture.mjs')], env: {} }], browser: { executable: '/unused-chrome', cefExecutable: resolve(binary), nodeExecutable: node, mcpScript: resolve(import.meta.dir, '../browser-tools/runner.mjs') } };
const portal = await Portal.open(config, { terminalBackend: false, browserBackend: backend });
const server = startPortalServer(portal);
const sockets: RpcSocket[] = [];
const evidence: Record<string, unknown> = {};
const assert = (value: unknown, reason: string) => { if (!value) throw new Error(reason); };
const timeout = setTimeout(() => { console.error('Acceptance timeout'); process.exit(1); }, 120_000);
try {
  const { profile } = await backend.profile('browser.profile.create', { name: 'Work identity' });
  const { profile: denied } = await backend.profile('browser.profile.create', { name: 'Personal identity' });
  const key = await generatePortalKey();
  const paired = await portal.security.redeemPairing({ type: PORTAL_PAIR_REQUEST_TYPE, token: await portal.security.createPairingToken(60_000), label: 'Acceptance human', publicKey: key.publicKey });
  const credential = { ...key, credentialId: paired.principal.credentialId };
  const base = `ws://127.0.0.1:${server.addr.port}`;
  const rpc = await RpcSocket.open(base + '/rpc', credential); sockets.push(rpc);
  // Exercise optional storage through the same authenticated RPCs used by Alpha.
  let optionalComposition = (await rpc.request('workspace.composition.get', { hostId: portal.security.hostId }) as any).composition;
  const created: any = await rpc.request('browser.pane.create', { hostId:portal.security.hostId,workspaceId:crypto.randomUUID(),workspaceName:'Temporary acceptance',expectedRevision:optionalComposition.revision,paneId:crypto.randomUUID(),url:'about:blank',axis:'vertical' });
  assert(created.page.temporary && !created.page.profileLocked, 'Blank Pane required a named Profile');
  const selected: any = await rpc.request('browser.pane.profile',{hostId:portal.security.hostId,expectedRevision:created.composition.revision,paneId:created.page.pageId,profileId:created.page.profileId,selectedProfileId:profile.profileId});
  assert(!selected.page.temporary && !selected.page.profileLocked,'Blank Profile selection was locked');
  await rpc.request('browser.page.navigate',{profileId:profile.profileId,pageId:selected.page.pageId,generation:selected.page.generation!,url:`http://127.0.0.1:${fixture.port}/`});
  let locked=false;
  try { await rpc.request('browser.pane.profile',{hostId:portal.security.hostId,expectedRevision:selected.composition.revision,paneId:selected.page.pageId,profileId:profile.profileId,selectedProfileId:denied.profileId}); } catch (error) { locked=String(error).includes('locked'); }
  assert(locked,'Named navigation did not lock Profile selection');
  optionalComposition=(await rpc.request('workspace.composition.get',{hostId:portal.security.hostId}) as any).composition;
  await rpc.request('browser.pane.close',{hostId:portal.security.hostId,expectedRevision:optionalComposition.revision,paneId:selected.page.pageId,profileId:profile.profileId,generation:selected.page.generation,confirmed:true});
  assert(!(await backend.profile('browser.profile.list',{})).profiles.some(item=>item.profileId===created.page.profileId),'Temporary identity survived its Pane');
  evidence.optionalProfileAndLock=true;
  Bun.gc(true); // Reclaimed process handles must not close a later runtime’s CDP pipes.
  const createThread = async () => {
    const { thread } = await rpc.request('thread.create', { executionContextId: 'context', agentId: 'fixture' }) as any;
    const { composition } = await rpc.request('workspace.composition.get', { hostId: portal.security.hostId }) as any;
    const workspace = composition.workspaces.find((item: any) => item.workspaceId === thread.workspaceId);
    const existing = paneTargets([workspace]).find(pane => pane.kind === 'agent' && pane.threadId === thread.threadId);
    const pane = existing ?? { kind: 'agent', nodeId: crypto.randomUUID(), paneId: crypto.randomUUID(), threadId: thread.threadId };
    if (!existing) workspace.layout = workspace.layout ? { kind: 'split', nodeId: crypto.randomUUID(), axis: 'vertical', ratio: .5, children: [workspace.layout, pane] } : pane;
    await rpc.request('workspace.composition.replace', { hostId: portal.security.hostId, expectedRevision: composition.revision, workspaces: composition.workspaces });
    const { connection } = await rpc.request('thread.attach', { threadId: thread.threadId }) as any;
    const acp = await RpcSocket.open(`${base}${connection.path}?threadId=${thread.threadId}`, credential); sockets.push(acp);
    await acp.request('initialize', { protocolVersion: 1, clientCapabilities: {} });
    await acp.request('session/load', { sessionId: thread.acpSessionId, cwd: root, mcpServers: [] });
    return { thread, acp, pane };
  };
  await backend.managedPage('page.create', { profileId: profile.profileId, pageId: crypto.randomUUID(), url: `http://127.0.0.1:${fixture.port}/?human=1` });
  Bun.gc(true);
  const a = await createThread();
  const tool = async (agent: typeof a, name: string, args: object = {}, allowError = false) => {
    let text = '';
    agent.acp.onNotification = message => { const update = (message.params as any)?.update; if (update?.sessionUpdate === 'agent_message_chunk') text += update.content.text; };
    await agent.acp.request('session/prompt', { sessionId: agent.thread.acpSessionId, prompt: [{ type: 'text', text: JSON.stringify({ name, arguments: args }) }] });
    const result = JSON.parse(text); if (!allowError) assert(!result.isError, `${name}: ${JSON.stringify(result)}`);
    console.log(name, result.isError ? 'rejected' : 'ok'); return result;
  };
  const tools = await tool(a, 'tools/list'); assert(tools.tools.some((tool: any) => tool.name === 'take_snapshot'), 'Maintained MCP tools missing'); evidence.toolCount = tools.tools.length;
  assert(tools.instructions?.includes('Weave Agent Pane'), 'MCP initialization lacks Weave browser context');
  assert(tools.tools.find((tool: any) => tool.name === 'list_pages').description.startsWith('Weave Browser Panes:'), 'Tool discovery lacks Weave browser context');
  let profiles = await tool(a, 'weave_browser_profiles'); assert(JSON.parse(profiles.content[0].text).profiles.length === 2, 'Agent cannot discover all Host Profiles');
  await tool(a, 'weave_browser_connect', { profileId: denied.profileId });
  const blocked = await tool(a, 'weave_browser_connect', { profileId: crypto.randomUUID() }, true); assert(blocked.isError, 'Unknown Profile selection permitted');
  await tool(a, 'weave_browser_connect', { profileId: profile.profileId });
  const existing = await tool(a, 'list_pages');
  assert(JSON.stringify(existing).includes('?human=1'), 'MCP omitted the pre-existing human page on first connection');
  const humanSnapshot = await tool(a, 'take_snapshot');
  assert(JSON.stringify(humanSnapshot).includes('Shared page'), 'MCP could not inspect the pre-existing human page');
  evidence.existingHumanPage = true;
  await tool(a, 'new_page', { url: `http://127.0.0.1:${fixture.port}/` });
  const snapshot = await tool(a, 'take_snapshot'); evidence.snapshot = snapshot.content;
  const evaluated = await tool(a, 'evaluate_script', { function: '() => { document.querySelector("button").click(); return document.querySelector("h1").textContent; }' });
  assert(JSON.stringify(evaluated).includes('Agent clicked'), 'Agent did not mutate real page');
  evidence.console = (await tool(a, 'list_console_messages')).content;
  evidence.network = (await tool(a, 'list_network_requests')).content;
  assert(JSON.stringify(evidence.console).includes('agent-console-evidence'), 'Console event missing');
  assert(JSON.stringify(evidence.network).includes('/api'), 'Network request missing');
  const screenshot = await tool(a, 'take_screenshot', { format: 'png' });
  const image = screenshot.content.find((item: any) => item.type === 'image'); assert(image?.data, 'No screenshot image');
  await writeFile(process.env.BROWSER_AGENT_SCREENSHOT ?? '/tmp/wve79-agent-screenshot.png', Buffer.from(image.data, 'base64'));
  const { pages } = await backend.managedPage('page.list', { profileId: profile.profileId });
  const page = pages.find((item: any) => item.url === `http://127.0.0.1:${fixture.port}/`); assert(page, 'Agent page is not Host-owned');
  const { composition } = await rpc.request('workspace.composition.get', { hostId: portal.security.hostId }) as any;
  assert(paneTargets(composition.workspaces).some(pane => pane.kind === 'browser' && pane.paneId === page.pageId), 'Agent page missing from composition');
  evidence.rightSplit = composition.workspaces.find((item: any) => item.workspaceId === a.thread.workspaceId).layout;
  const cdp = async (method: string, params = {}, sessionId?: string) => JSON.parse((await tool(a, 'weave_browser_cdp', { method, params, sessionId })).content[0].text);
  const target = await backend.managedPage('page.cdp', { pageId: page.pageId, generation: page.generation, arguments: { method: 'Target.getTargetInfo', arguments: {} } });
  const attached = await cdp('Target.attachToTarget', { targetId: target.targetInfo.targetId, flatten: true });
  const sessionId = attached.response.result.sessionId;
  await cdp('Debugger.enable', {}, sessionId);
  const paused = async (result: any) => {
    const deadline = Date.now() + 5000;
    while (!result.events?.some((event: any) => event.method === 'Debugger.paused' && event.sessionId === sessionId)) {
      if (Date.now() > deadline) throw new Error('Debugger did not pause');
      await Bun.sleep(25);
      result = JSON.parse((await tool(a, 'weave_browser_cdp')).content[0].text);
    }
  };
  await paused(await cdp('Debugger.pause', {}, sessionId));
  await paused(await cdp('Debugger.stepOver', {}, sessionId));
  await cdp('Debugger.resume', {}, sessionId); evidence.debuggerStepping = true;
  const b = await createThread();
  profiles = await tool(b, 'weave_browser_profiles'); assert(JSON.parse(profiles.content[0].text).profiles.length === 2, 'Second Thread cannot access all Host Profiles'); evidence.allProfilesWithoutGrants = true;
  const before = await backend.managedPage('page.cdp', { pageId: page.pageId, generation: page.generation, arguments: { method: 'Runtime.evaluate', arguments: { expression: 'ticks', returnByValue: true } } });
  await Bun.sleep(200);
  const after = await backend.managedPage('page.cdp', { pageId: page.pageId, generation: page.generation, arguments: { method: 'Runtime.evaluate', arguments: { expression: 'ticks', returnByValue: true } } });
  assert(after.result.value > before.result.value, 'Unattended page stopped'); evidence.unattended = true;
  await tool(a, 'evaluate_script', { function: '() => document.title' });
  const surviving = await backend.managedPage('page.list', { profileId: profile.profileId }); assert(surviving.pages.some((item: any) => item.pageId === page.pageId && item.available), 'Shared page stopped'); evidence.sharedPageSurvives = true;
  const beforeClose = (await tool(a, 'list_pages')).content.filter((item: any) => item.type === 'text').map((item: any) => item.text).join('\n');
  const selectedLine = beforeClose.match(/^(\d+):[^\n]*?\[selected\]/m);
  assert(selectedLine, 'Maintained tool did not identify its selected page');
  await tool(a, 'close_page', { pageId: Number(selectedLine![1]) });
  assert(!(await backend.managedPage('page.list', {})).pages.some((item: any) => item.pageId === page.pageId), 'Agent close left the Host page alive');
  const closedComposition = (await rpc.request('workspace.composition.get', { hostId: portal.security.hostId }) as any).composition;
  assert(!paneTargets(closedComposition.workspaces).some(pane => pane.kind === 'browser' && pane.paneId === page.pageId), 'Agent close left its Pane in composition');
  evidence.agentCloseRemovesPageAndPane = true;
  await writeFile(process.env.BROWSER_AGENT_EVIDENCE ?? '/tmp/wve79-agent-acceptance.json', JSON.stringify(evidence, null, 2) + '\n');
  console.log('Browser ACP/MCP acceptance passed');
} finally {
  clearTimeout(timeout); for (const socket of sockets) socket.close(); await server.shutdown(); await portal.close(); await owner.close(); await fixture.stop(true); await rm(root, { recursive: true, force: true });
}
