import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { pairPortalCredential, RpcSocket, waitFor } from './rpc-client.ts';
const [binary, upgrade, root] = process.argv.slice(2);
assert(binary && upgrade && root, 'Usage: service-acceptance <Host> <upgrade Host> <isolated root>');
const config = join(root, 'host.json');
const name = 'wve46-acceptance';
const url = 'ws://127.0.0.1:43146';
const command = async (args: string[]) => {
  const child = Bun.spawn(args, { stdout: 'pipe', stderr: 'pipe' });
  const [output, error, code] = await Promise.all([new Response(child.stdout).text(), new Response(child.stderr).text(), child.exited]);
  assert.equal(code, 0, error);
  return output.trim();
};
const service = (action: string, args: string[] = []) => command([binary, 'service', action, '--name', name, ...args]);
const health = async () => await (await fetch('http://127.0.0.1:43146/health')).json() as any;
const initial = await health();
const token = await command([binary, 'pairing', 'create', '--config', config]);
const credential = await pairPortalCredential(url, token, 'Service acceptance');
let rpc = await RpcSocket.open(`${url}/rpc`, credential);
const thread = (await rpc.request('thread.create', { executionContextId: 'service', agentId: 'fixture', title: 'Service acceptance' }) as any).thread;
const terminal = (await rpc.request('terminal.create', { executionContextId: 'service', cols: 90, rows: 30 }) as any).terminal;
const scope = { executionContextId: 'service', terminalId: terminal.terminalId };
const attachment = await rpc.request('terminal.attach', { ...scope, mode: 'shared' }) as any;
await rpc.request('terminal.input', { ...scope, attachmentId: attachment.attachment.attachmentId, data: new TextEncoder().encode("WEAVE_SERVICE_MARKER=SERVICE_STATE_RETAINED\n") });
await Bun.sleep(200);
const verify = async (phase: string) => {
  rpc.close();
  await waitFor(async () => { try { return (await health()).hostId === initial.hostId; } catch { return false; } });
  rpc = await RpcSocket.open(`${url}/rpc`, credential);
  assert(JSON.stringify(await rpc.request('thread.list')).includes(thread.threadId));
  const attached = await rpc.request('terminal.attach', { ...scope, mode: 'shared' }) as any;
  assert.equal(new TextDecoder().decode(attached.snapshot.data.subarray(0, 8)), 'GHOSTSNP');
  await rpc.request('terminal.input', { ...scope, attachmentId: attached.attachment.attachmentId, data: new TextEncoder().encode("printf 'CHECK:%s\\n' \"$WEAVE_SERVICE_MARKER\"\n") });
  await waitFor(() => rpc.notifications.some((message: any) => message.params?.event?.type === 'output' && new TextDecoder().decode(message.params.event.data).includes('CHECK:SERVICE_STATE_RETAINED')));
  console.log(JSON.stringify({ phase, hostIdentity: true, credential: true, thread: true, terminal: true }));
  return attached;
};
rpc.close();
await service('restart');
await verify('restart');
rpc.close();
const pid = await command(['systemctl', '--user', 'show', 'weave-host-wve46-acceptance.service', '--property=MainPID', '--value']);
process.kill(Number(pid), 'SIGKILL');
await Bun.sleep(3500);
await verify('crash and stale socket recovery');
rpc.close();
await service('upgrade', ['--binary', upgrade]);
assert.notEqual((await health()).build.revision, initial.build.revision);
await verify('upgrade');
rpc.close();
await service('rollback');
assert.equal((await health()).build.revision, initial.build.revision);
const finalAttachment = await verify('rollback');
await rpc.request('terminal.close', { ...scope, attachmentId: finalAttachment.attachment.attachmentId });
rpc.close();
await service('stop');
await assert.rejects(health);
await service('start');
await waitFor(async () => { try { return (await health()).hostId === initial.hostId; } catch { return false; } });
await service('uninstall');
await assert.rejects(health);
assert((await readFile(join(root, 'state/threads.json'), 'utf8')).includes(thread.threadId));
assert((await readFile(join(root, 'state/security.json'), 'utf8')).includes(credential.credentialId));
console.log(JSON.stringify({ phase: 'stop/start/uninstall', passed: true, durableStateRetained: true }));
