export const browserScrollFixture = `<!doctype html><meta charset="utf-8"><title>Lossless scrolling benchmark</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#eff1f5;color:#303446;font:16px/1.5 system-ui}header{position:sticky;top:0;background:#fab387;padding:12px;z-index:1}main{max-width:1000px;padding:20px;margin:auto}section{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-bottom:20px;border-bottom:1px solid #8991a0}pre{background:#303446;color:#a6d189;padding:12px;white-space:pre-wrap}.nested{height:130px;overflow:auto;border:2px solid #7287fd}svg{width:100%;height:180px}#marker{position:fixed;top:0;left:0;width:2px;height:1px;z-index:100}#bar{position:fixed;bottom:0;width:70px;height:8px;background:#df8e1d;z-index:5}
</style><canvas id="marker" width="2" height="1"></canvas><header>Weave · sharp text, sticky header, nested overflow, code and images</header><main></main><div id="bar"></div>
<script>
document.querySelector('main').innerHTML=Array.from({length:160},(_,i)=>'<section><div><h2>Section '+i+' · Browser Pane</h2><p>Small text and punctuation: Il1 O0 {} [] () → ✓. A persistent Host Profile owns this page.</p><div class="nested">'+Array.from({length:12},(_,j)=>'<p>Nested row '+j+' – scroll within this panel</p>').join('')+'</div></div><div><pre>async function focus(view) {\\n  await host.claimViewport(view);\\n  return { width: 1147, height: 849 };\\n}</pre><svg viewBox="0 0 500 180"><defs><linearGradient id="g'+i+'"><stop stop-color="#7287fd"/><stop offset="1" stop-color="#fab387"/></linearGradient></defs><rect width="500" height="180" fill="url(#g'+i+')"/><circle cx="250" cy="90" r="65" fill="#40a02b"/><text x="20" y="100" font-size="25">Lossless pixels '+i+'</text></svg></div></section>').join('');
const ctx=document.querySelector('#marker').getContext('2d'),image=ctx.createImageData(2,1),bar=document.querySelector('#bar');let seq=0;window.fixtureRunning=true;window.fixtureFrames=0;
function tick(){if(!window.fixtureRunning)return;const values=[Math.round(scrollY),++seq];for(let i=0;i<2;i++){let n=values[i];image.data.set([(n>>16)&255,(n>>8)&255,n&255,255],i*4)}ctx.putImageData(image,0,0);bar.style.left=(seq*3%(innerWidth-70))+'px';window.fixtureFrames++;requestAnimationFrame(tick)}tick();
</script>`;
