import { mkdir } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { prepareNodeApiHeaders } from '../../scripts/native-headers';
const root = resolve(import.meta.dir, '..');
const build = join(root, 'native/.build/client-browser');
await mkdir(build, { recursive: true });
const headers = await prepareNodeApiHeaders((await Bun.file(join(root, 'package.json')).json()).devDependencies.electron);
const run = async (args: string[]) => { const child = Bun.spawn(args, { stdout: 'inherit', stderr: 'inherit' }); if (await child.exited) throw new Error(`Failed: ${args[1]}`); };
const target = `${process.arch === 'arm64' ? 'arm64' : 'x86_64'}-apple-macosx26.0`;
await run(['xcrun', 'swiftc', '-swift-version', '6', '-D', 'WEAVE_CLIENT_BROWSER_PROTOTYPE', '-target', target, '-parse-as-library', '-emit-module', '-emit-object', '-module-name', 'WeaveClientBrowser', '-emit-module-path', join(build,'WeaveClientBrowser.swiftmodule'), '-emit-objc-header-path', join(build,'WeaveClientBrowser-Swift.h'), join(root,'native/client-browser/ClientBrowserPrototype.swift'), '-o', join(build,'browser.o')]);
await run(['xcrun','clang++','-target',target,'-std=c++17','-fobjc-arc','-fmodules','-c','-I',headers,'-I',build,join(root,'native/client-browser/electron-client-browser.mm'),'-o',join(build,'addon.o')]);
await run(['xcrun','swiftc','-target',target,'-emit-library',join(build,'browser.o'),join(build,'addon.o'),'-Xlinker','-undefined','-Xlinker','dynamic_lookup','-framework','AppKit','-framework','SwiftUI','-framework','WebKit','-o',join(build,'weave-client-browser.node')]);
