import { renameThreadTool } from '../tools/rename-thread-tool';
import { updateProposalTool, writeProposalTool } from '../tools/proposal-tool';
import { updatePlanTool, writePlanTool } from '../tools/update-plan-tool';
import { webExtractTool, webSearchTool } from '../tools/web-search-tools';
import {
  gitBranchTool,
  gitDiffTool,
  gitLogTool,
  gitShowTool,
  gitStatusTool,
  gitSwitchTool,
  gitWorktreeTool,
} from '../tools/git-tools';
import {
  portalBashTool,
  portalEditTool,
  portalReadTool,
  portalWriteTool,
  vaultDeleteTool,
  vaultIndexTool,
  vaultMkdirTool,
  vaultMoveTool,
  vaultReadTool,
  vaultUploadTool,
  vaultWriteTool,
} from '../tools/portal-tools';
import {
  codeActionPreviewTool,
  codeActionsTool,
  codeDefinitionTool,
  codeDiagnosticsTool,
  codeHoverTool,
  codeIntelCapabilitiesTool,
  codeReferencesTool,
  codeSymbolsTool,
  formatPreviewTool,
  renamePreviewTool,
  workspaceSymbolsTool,
} from '../tools/language-intelligence-tools';

export const mageHandTools = {
  renameThreadTool,
  writePlanTool,
  updatePlanTool,
  writeProposalTool,
  updateProposalTool,
  webSearch: webSearchTool,
  webExtract: webExtractTool,
  read: portalReadTool,
  write: portalWriteTool,
  edit: portalEditTool,
  bash: portalBashTool,
  git_status: gitStatusTool,
  git_diff: gitDiffTool,
  git_log: gitLogTool,
  git_show: gitShowTool,
  git_branch: gitBranchTool,
  git_switch: gitSwitchTool,
  git_worktree: gitWorktreeTool,
  code_intel_capabilities: codeIntelCapabilitiesTool,
  code_diagnostics: codeDiagnosticsTool,
  code_hover: codeHoverTool,
  code_definition: codeDefinitionTool,
  code_references: codeReferencesTool,
  code_symbols: codeSymbolsTool,
  workspace_symbols: workspaceSymbolsTool,
  code_actions: codeActionsTool,
  code_action_preview: codeActionPreviewTool,
  rename_preview: renamePreviewTool,
  format_preview: formatPreviewTool,
  vault_index: vaultIndexTool,
  vault_read: vaultReadTool,
  vault_write: vaultWriteTool,
  vault_mkdir: vaultMkdirTool,
  vault_move: vaultMoveTool,
  vault_delete: vaultDeleteTool,
  vault_upload: vaultUploadTool,
};
