import { renameThreadTool } from '../tools/rename-thread-tool';
import { updateProposalTool, writeProposalPatchTool, writeProposalTool } from '../tools/proposal-tool';
import { updatePlanTool, writePlanTool } from '../tools/update-plan-tool';
import { webExtractTool, webSearchTool } from '../tools/web-search-tools';
import {
  gitBranchTool,
  gitDiffTool,
  gitLogTool,
  gitShowTool,
  gitStatusTool,
  gitSwitchTool,
  gitWorktreeTool,
} from '../tools/git-tools';
import {
  portalBashTool,
  portalEditTool,
  portalReadTool,
  portalWriteTool,
  fileDeleteTool,
  fileIndexTool,
  fileMkdirTool,
  fileMoveTool,
  fileReadTool,
  fileUploadTool,
  fileWriteTool,
} from '../tools/portal-tools';
import {
  codeActionPreviewTool,
  codeActionsTool,
  codeDefinitionTool,
  codeDiagnosticsTool,
  codeHoverTool,
  codeIntelCapabilitiesTool,
  codeReferencesTool,
  codeSymbolsTool,
  formatPreviewTool,
  renamePreviewTool,
  workspaceSymbolsTool,
} from '../tools/language-intelligence-tools';
import { editorContextTool } from '../tools/editor-context-tools';

export const mageHandTools = {
  renameThreadTool,
  writePlanTool,
  updatePlanTool,
  writeProposalTool,
  writeProposalPatchTool,
  updateProposalTool,
  webSearch: webSearchTool,
  webExtract: webExtractTool,
  editor_context: editorContextTool,
  read: portalReadTool,
  write: portalWriteTool,
  edit: portalEditTool,
  bash: portalBashTool,
  git_status: gitStatusTool,
  git_diff: gitDiffTool,
  git_log: gitLogTool,
  git_show: gitShowTool,
  git_branch: gitBranchTool,
  git_switch: gitSwitchTool,
  git_worktree: gitWorktreeTool,
  code_intel_capabilities: codeIntelCapabilitiesTool,
  code_diagnostics: codeDiagnosticsTool,
  code_hover: codeHoverTool,
  code_definition: codeDefinitionTool,
  code_references: codeReferencesTool,
  code_symbols: codeSymbolsTool,
  workspace_symbols: workspaceSymbolsTool,
  code_actions: codeActionsTool,
  code_action_preview: codeActionPreviewTool,
  rename_preview: renamePreviewTool,
  format_preview: formatPreviewTool,
  file_index: fileIndexTool,
  file_read: fileReadTool,
  file_write: fileWriteTool,
  file_mkdir: fileMkdirTool,
  file_move: fileMoveTool,
  file_delete: fileDeleteTool,
  file_upload: fileUploadTool,
};
