import { chmod, mkdir, statSync, writeText } from './host-files.ts';
import { isFsError } from './host-files.ts';
import { spawnProcess, runProcess } from './host-process.ts';
import type { HostProcess } from './host-process.ts';
import { dirname, join } from 'node:path';
import type { TerminalBackend, TerminalBackendEvent, TerminalBackendRecord } from './terminals.ts';

type CommandResult = { code: number; stdout: string; stderr: string };
type TmuxRunner = (
  args: string[],
  options?: { cwd?: string; env?: Record<string, string> },
) => Promise<CommandResult>;

type TmuxRecord = TerminalBackendRecord & {
  paneId: string;
  windowId: string;
  cwd: string;
};

type UnsequencedTerminalBackendEvent =
  | { terminalId: string; type: 'output'; data: string }
  | { terminalId: string; type: 'title'; title: string; processName?: string }
  | { terminalId: string; type: 'exit'; exitCode?: number };

type ControlHandlers = {
  output: (paneId: string, data: string) => void;
  pause: (paneId: string) => void;
  windowClosed: (windowId: string) => void;
  boundary: () => number;
  exited: () => void;
  error: (error: Error) => void;
};

type ControlCommandResult = { stdout: string; boundary: number };
type ControlClient = {
  command(command: string): Promise<ControlCommandResult>;
  commands(commands: string[]): Promise<ControlCommandResult[]>;
  close(): void;
};
type ControlClientFactory = (input: {
  executable: string;
  args: string[];
  env: Record<string, string>;
  handlers: ControlHandlers;
}) => Promise<ControlClient>;

type TmuxTerminalBackendOptions = {
  stateDirectory: string;
  env?: Record<string, string | undefined>;
  runner?: TmuxRunner;
  controlClientFactory?: ControlClientFactory;
};

const encoder = new TextEncoder();
const decoder = new TextDecoder();
const SESSION_NAME = '_weave_product';
const CONFIG_VERSION = 'weave-product-terminal-v1';
const TMUX_REQUIRED = 'tmux is required for Weave terminals but was not found on PATH.';
const MAX_SAFE_UNIX_SOCKET_BYTES = 96;

const executableFile = (path: string) => {
  try {
    const stat = statSync(path);
    return stat.isFile() && (stat.mode === null || (stat.mode & 0o111) !== 0);
  } catch {
    return false;
  }
};

export const resolveTmuxExecutable = (
  env: Record<string, string | undefined>,
  options: {
    os?: NodeJS.Platform;
    isExecutable?: (path: string) => boolean;
  } = {},
) => {
  const configured = env.WEAVE_PORTAL_TMUX_PATH?.trim();
  if (configured) return configured;
  const isExecutable = options.isExecutable ?? executableFile;
  const pathCandidates = (env.PATH ?? '')
    .split(':')
    .filter(Boolean)
    .map((directory) => join(directory, 'tmux'));
  const platformCandidates = (options.os ?? process.platform) === 'darwin'
    ? ['/opt/homebrew/bin/tmux', '/usr/local/bin/tmux', '/usr/bin/tmux']
    : ['/usr/local/bin/tmux', '/usr/bin/tmux'];
  return [...new Set([...pathCandidates, ...platformCandidates])].find(isExecutable) ?? 'tmux';
};

const shellQuote = (value: string) => `'${value.replaceAll("'", "'\\''")}'`;

const stableSocketPath = (stateDirectory: string) => {
  const preferred = join(stateDirectory, 'terminal', 'tmux.sock');
  if (encoder.encode(preferred).byteLength <= MAX_SAFE_UNIX_SOCKET_BYTES) return preferred;
  let hash = 0xcbf29ce484222325n;
  for (const byte of encoder.encode(stateDirectory)) {
    hash ^= BigInt(byte);
    hash = BigInt.asUintN(64, hash * 0x100000001b3n);
  }
  return `/tmp/weave-product-tmux-${hash.toString(16).padStart(16, '0')}.sock`;
};
const commandEnvironment = (source: Record<string, string | undefined>) => {
  const env = Object.fromEntries(
    Object.entries(source).filter((entry): entry is [string, string] =>
      typeof entry[1] === 'string' && entry[0] !== 'NO_COLOR' && entry[0] !== 'TMUX' && entry[0] !== 'TMUX_PANE'
    ),
  );
  if (!env.LC_ALL && !env.LC_CTYPE && !env.LANG) env.LANG = 'C.UTF-8';
  return env;
};

const validTerminalName = (value: string | undefined) =>
  value && /^[A-Za-z0-9][A-Za-z0-9_.+-]*$/.test(value) ? value : undefined;

const terminalAvailable = async (name: string, env: Record<string, string>) => {
  try {
    const result = await runProcess('infocmp', {
      args: [name],
      env,
      stdout: 'ignore',
      stderr: 'ignore',
    });
    return result.success;
  } catch {
    return false;
  }
};

const resolveDefaultTerminal = async (source: Record<string, string | undefined>) => {
  const env = commandEnvironment(source);
  const override = validTerminalName(source.WEAVE_PORTAL_TMUX_TERM);
  if (override) return override;
  if (await terminalAvailable('tmux-256color', env)) return 'tmux-256color';
  return 'screen-256color';
};

const buildConfig = (defaultTerminal: string) =>
  `# Generated by Weave. Do not edit.
set-option -g status off
set-option -g prefix None
set-option -g prefix2 None
unbind-key -aT root
unbind-key -aT prefix
unbind-key -aT copy-mode
unbind-key -aT copy-mode-vi
set-option -g mouse off
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g bell-action none
set-option -g detach-on-destroy on
set-option -g base-index 0
set-option -g renumber-windows off
set-window-option -g automatic-rename off
set-window-option -g allow-rename off
set-option -g set-titles off
set-option -g default-terminal "${defaultTerminal}"
set-option -ga terminal-overrides ",${defaultTerminal}:Tc"
set-environment -gu NO_COLOR
set-option -g @weave_product_terminal_config ${CONFIG_VERSION}
`;

const encodeInputHex = (data: string) => [...encoder.encode(data)].map((byte) => byte.toString(16).padStart(2, '0'));

const decodeControlBytes = (value: string) => {
  const bytes: number[] = [];
  for (let index = 0; index < value.length;) {
    if (value[index] !== '\\') {
      const point = value.codePointAt(index);
      if (point === undefined) break;
      bytes.push(...encoder.encode(String.fromCodePoint(point)));
      index += point > 0xffff ? 2 : 1;
      continue;
    }
    const octal = value.slice(index + 1, index + 4);
    if (/^[0-7]{3}$/.test(octal)) {
      bytes.push(Number.parseInt(octal, 8));
      index += 4;
      continue;
    }
    const escaped = value[index + 1];
    if (escaped === undefined) {
      bytes.push(92);
      index += 1;
    } else {
      bytes.push(...encoder.encode(escaped));
      index += 2;
    }
  }
  return new Uint8Array(bytes);
};

type CompatibilityMode = 'text' | 'escape' | 'legacy-title' | 'legacy-title-escape';

const filterLegacyTitle = (bytes: Uint8Array, state: { mode: CompatibilityMode }) => {
  const output: number[] = [];
  for (const byte of bytes) {
    if (state.mode === 'text') {
      if (byte === 0x1b) state.mode = 'escape';
      else output.push(byte);
      continue;
    }
    if (state.mode === 'escape') {
      if (byte === 0x6b) {
        state.mode = 'legacy-title';
      } else {
        output.push(0x1b);
        if (byte === 0x1b) state.mode = 'escape';
        else {
          output.push(byte);
          state.mode = 'text';
        }
      }
      continue;
    }
    if (state.mode === 'legacy-title') {
      if (byte === 0x1b) state.mode = 'legacy-title-escape';
      else if (byte === 0x07 || byte === 0x9c) state.mode = 'text';
      continue;
    }
    if (byte === 0x5c) state.mode = 'text';
    else if (byte !== 0x1b) state.mode = 'legacy-title';
  }
  return new Uint8Array(output);
};

class OutputDecoder {
  readonly #streams = new Map<string, { decoder: TextDecoder; compatibility: { mode: CompatibilityMode } }>();

  decode(paneId: string, value: string) {
    let stream = this.#streams.get(paneId);
    if (!stream) {
      stream = { decoder: new TextDecoder(), compatibility: { mode: 'text' } };
      this.#streams.set(paneId, stream);
    }
    return stream.decoder.decode(
      filterLegacyTitle(decodeControlBytes(value), stream.compatibility),
      { stream: true },
    );
  }
}

class TmuxControlClient implements ControlClient {
  readonly #process: HostProcess;
  readonly #writer: WritableStreamDefaultWriter<Uint8Array>;
  readonly #ready: Promise<void>;
  readonly #pending: Array<{
    resolve: (result: ControlCommandResult) => void;
    reject: (error: Error) => void;
  }> = [];
  #active?: {
    resolve: (result: ControlCommandResult) => void;
    reject: (error: Error) => void;
    boundary: number;
    output: string[];
  };
  #resolveReady!: () => void;
  #commandQueue: Promise<unknown> = Promise.resolve();
  #isReady = false;
  #closed = false;

  private constructor(process: HostProcess, private readonly handlers: ControlHandlers) {
    this.#process = process;
    this.#writer = process.stdin.getWriter();
    this.#ready = new Promise((resolve) => {
      this.#resolveReady = resolve;
    });
  }

  static async open(input: {
    executable: string;
    args: string[];
    env: Record<string, string>;
    handlers: ControlHandlers;
  }) {
    let process: HostProcess;
    try {
      process = spawnProcess(input.executable, {
        args: input.args,
        env: input.env,
          stdin: 'pipe',
        stdout: 'pipe',
        stderr: 'pipe',
      });
    } catch (cause) {
      if (isFsError(cause, 'ENOENT')) throw new Error(TMUX_REQUIRED);
      throw cause;
    }
    const client = new TmuxControlClient(process, input.handlers);
    client.#read(process.stdout);
    void process.stderr.pipeTo(new WritableStream({ write() {} })).catch(() => undefined);
    void process.status.then(() => {
      if (!client.#closed) input.handlers.exited();
    }).catch((cause) => {
      if (!client.#closed) input.handlers.error(cause instanceof Error ? cause : new Error(String(cause)));
    });
    await client.#ready;
    return client;
  }

  command(command: string) {
    return this.commands([command]).then(([result]) => result);
  }

  commands(commands: string[]) {
    const result = this.#commandQueue.then(async () => {
      await this.#ready;
      if (this.#closed) throw new Error('tmux control client is closed.');
      const responses = commands.map(() =>
        new Promise<ControlCommandResult>((resolve, reject) => {
          this.#pending.push({ resolve, reject });
        })
      );
      try {
        await this.#writer.write(encoder.encode(`${commands.join('\n')}\n`));
      } catch (cause) {
        const error = cause instanceof Error ? cause : new Error(String(cause));
        for (const pending of this.#pending.splice(-commands.length)) pending.reject(error);
      }
      return await Promise.all(responses);
    });
    this.#commandQueue = result.then(() => undefined, () => undefined);
    return result;
  }

  close() {
    if (this.#closed) return;
    this.#closed = true;
    const error = new Error('tmux control client closed.');
    this.#active?.reject(error);
    this.#active = undefined;
    for (const pending of this.#pending.splice(0)) pending.reject(error);
    void this.#writer.write(encoder.encode('detach-client\n')).catch(() => undefined).finally(() => {
      void this.#writer.close().catch(() => undefined);
    });
    setTimeout(() => {
      try {
        this.#process.kill('SIGTERM');
      } catch {
        // The control client may already have exited after detach-client.
      }
    }, 250);
  }

  #read(stream: ReadableStream<Uint8Array>) {
    const outputDecoder = new OutputDecoder();
    void (async () => {
      const reader = stream.getReader();
      const textDecoder = new TextDecoder();
      let buffered = '';
      try {
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;
          buffered += textDecoder.decode(value, { stream: true });
          const lines = buffered.split(/\r?\n/);
          buffered = lines.pop() ?? '';
          for (const line of lines) this.#line(line, outputDecoder);
        }
      } catch (cause) {
        if (!this.#closed) this.handlers.error(cause instanceof Error ? cause : new Error(String(cause)));
      }
    })();
  }

  #line(line: string, outputDecoder: OutputDecoder) {
    const output = /^%(?:extended-)?output\s+(\S+)(?:\s+.*?\s:)?\s?(.*)$/.exec(line);
    if (output) {
      const data = outputDecoder.decode(output[1], output[2] ?? '');
      if (data) this.handlers.output(output[1], data);
      return;
    }
    const pause = /^%pause\s+(\S+)/.exec(line);
    if (pause) {
      this.handlers.pause(pause[1]);
      return;
    }
    const closed = /^%(?:unlinked-)?window-close\s+(\S+)/.exec(line);
    if (closed) {
      this.handlers.windowClosed(closed[1]);
      return;
    }
    if (/^%begin\s/.test(line)) {
      const pending = this.#pending.shift();
      if (pending) {
        this.#active = {
          ...pending,
          boundary: this.handlers.boundary(),
          output: [],
        };
      }
      return;
    }
    if (/^%end\s/.test(line)) {
      if (this.#active) {
        const active = this.#active;
        this.#active = undefined;
        active.resolve({
          stdout: active.output.length > 0 ? `${active.output.join('\n')}\n` : '',
          boundary: active.boundary,
        });
      } else if (!this.#isReady) {
        this.#isReady = true;
        this.#resolveReady();
      }
      return;
    }
    if (/^%error\s/.test(line)) {
      if (this.#active) {
        const active = this.#active;
        this.#active = undefined;
        active.reject(new Error(active.output.join('\n') || 'tmux control command failed.'));
      } else if (!this.#isReady) {
        this.#isReady = true;
        this.#resolveReady();
      }
      return;
    }
    this.#active?.output.push(line);
  }
}

export class TmuxTerminalBackend implements TerminalBackend {
  readonly #socketPath: string;
  readonly #configPath: string;
  readonly #executable: string;
  readonly #env: Record<string, string | undefined>;
  readonly #runner?: TmuxRunner;
  readonly #controlFactory: ControlClientFactory;
  readonly #listeners = new Set<(event: TerminalBackendEvent) => void>();
  readonly #recordsByPane = new Map<string, TmuxRecord>();
  readonly #recordsByWindow = new Map<string, TmuxRecord>();
  readonly #manuallyPausedPanes = new Set<string>();
  #controlClient?: ControlClient;
  #controlOpening?: Promise<void>;
  #configReady?: Promise<void>;
  #sessionQueue: Promise<void> = Promise.resolve();
  #eventSequence = 0;
  #disposed = false;

  constructor(options: TmuxTerminalBackendOptions) {
    this.#socketPath = stableSocketPath(options.stateDirectory);
    this.#configPath = join(options.stateDirectory, 'terminal', 'tmux.conf');
    this.#env = options.env ?? { ...process.env };
    this.#executable = resolveTmuxExecutable(this.#env);
    this.#runner = options.runner;
    this.#controlFactory = options.controlClientFactory ?? TmuxControlClient.open;
  }

  static async available(env: Record<string, string | undefined> = { ...process.env }) {
    try {
      return (await runProcess(resolveTmuxExecutable(env), {
        args: ['-V'],
        env: commandEnvironment(env),
          stdout: 'ignore',
        stderr: 'ignore',
      })).success;
    } catch {
      return false;
    }
  }

  async list() {
    await this.#ensureSession(process.env['HOME'] ?? process.cwd());
    const result = await this.#run(
      [
        'list-windows',
        '-t',
        SESSION_NAME,
        '-F',
        [
          '#{window_id}',
          '#{pane_id}',
          '#{@weave_terminal_id}',
          '#{@weave_workspace_id}',
          '#{@weave_cwd}',
          '#{window_name}',
          '#{pane_current_command}',
          '#{window_width}',
          '#{window_height}',
        ].join('\t'),
      ],
      {},
      [0, 1],
    );
    if (result.code !== 0) return [];
    const records = result.stdout.split('\n').flatMap((line): TmuxRecord[] => {
      const [windowId, paneId, terminalId, workspaceId, cwd, title, processName, colsText, rowsText] = line.split('\t');
      const cols = Number(colsText);
      const rows = Number(rowsText);
      if (
        !windowId || !paneId || !terminalId || !workspaceId || !cwd || !Number.isInteger(cols) ||
        !Number.isInteger(rows)
      ) {
        return [];
      }
      return [{
        terminalId,
        workspaceId,
        cwd,
        title: processName && processName !== 'zsh' && processName !== 'bash' && processName !== 'sh'
          ? processName
          : title || 'Terminal',
        processName: processName || undefined,
        status: 'running',
        cols,
        rows,
        paneId,
        windowId,
      }];
    });
    this.#index(records);
    return records.map(({ cwd: _cwd, ...record }) => record);
  }

  async create(input: {
    terminalId: string;
    workspaceId: string;
    cwd: string;
    cols: number;
    rows: number;
    env: Record<string, string>;
  }) {
    await this.#ensureSession(input.cwd);
    const shell = this.#env.SHELL?.trim() || '/bin/zsh';
    const processEnv = { ...commandEnvironment(this.#env), ...input.env };
    delete processEnv.NO_COLOR;
    const command = [
      '/usr/bin/env',
      '-u',
      'NO_COLOR',
      ...Object.entries(input.env).map(([key, value]) => `${key}=${value}`),
      shell,
      '-l',
    ].map(shellQuote).join(' ');
    const created = await this.#run([
      'new-window',
      '-d',
      '-P',
      '-F',
      '#{window_id}\t#{pane_id}',
      '-t',
      `${SESSION_NAME}:`,
      '-n',
      `terminal-${input.terminalId.slice(0, 8)}`,
      '-c',
      input.cwd,
      command,
    ], { cwd: input.cwd, env: processEnv });
    const [windowId, paneId] = created.stdout.trim().split('\t');
    if (!windowId || !paneId) {
      throw new Error(
        `tmux did not return the created Terminal window: stdout=${JSON.stringify(created.stdout)} ` +
          `stderr=${JSON.stringify(created.stderr)} code=${created.code}.`,
      );
    }
    for (
      const [name, value] of [
        ['@weave_terminal_id', input.terminalId],
        ['@weave_workspace_id', input.workspaceId],
        ['@weave_cwd', input.cwd],
      ]
    ) {
      await this.#run(['set-window-option', '-t', windowId, name, value], { cwd: input.cwd, env: processEnv });
    }
    await this.#run(
      ['resize-window', '-t', windowId, '-x', String(input.cols), '-y', String(input.rows)],
      { cwd: input.cwd, env: processEnv },
    );
    const records = await this.list();
    const record = records.find((candidate) => candidate.terminalId === input.terminalId);
    if (!record) throw new Error('Created tmux Terminal is unavailable.');
    await this.#ensureControlClient();
    return record;
  }

  async capture(terminalId: string) {
    await this.#ensureControlClient();
    const record = await this.#record(terminalId);
    const marker = `__WEAVE_CAPTURE_STATE_${crypto.randomUUID()}__`;
    const pause = ['refresh-client', '-A', `${record.paneId}:pause`].map(shellQuote).join(' ');
    const capture = ['capture-pane', '-p', '-e', '-J', '-S', '-', '-t', record.paneId]
      .map(shellQuote).join(' ');
    const state = ['display-message', '-p', '-t', record.paneId, `${marker}#{cursor_x}\t#{cursor_y}`]
      .map(shellQuote).join(' ');
    const resume = ['refresh-client', '-A', `${record.paneId}:continue`].map(shellQuote).join(' ');
    const client = this.#controlClient;
    if (!client) throw new Error('tmux control client is unavailable.');
    this.#manuallyPausedPanes.add(record.paneId);
    try {
      const [paused, captured, cursorState] = await client.commands([pause, capture, state, resume]);
      const value = cursorState.stdout.trimEnd();
      if (!value.startsWith(marker)) throw new Error('tmux did not return the Terminal capture state.');
      const [x = '', y = ''] = value.slice(marker.length).split('\t');
      const cursorX = Number(x);
      const cursorY = Number(y);
      if (!Number.isInteger(cursorX) || !Number.isInteger(cursorY)) {
        throw new Error('tmux returned invalid Terminal cursor coordinates.');
      }
      const screen = captured.stdout.replace(/\r?\n$/, '').replace(/\r?\n/g, '\r\n');
      return {
        data: `\x1b[2J\x1b[H${screen}\x1b[${cursorY + 1};${cursorX + 1}H`,
        boundary: paused.boundary,
      };
    } finally {
      this.#manuallyPausedPanes.delete(record.paneId);
    }
  }

  async input(terminalId: string, data: string) {
    const record = await this.#record(terminalId);
    const bytes = encodeInputHex(data);
    for (let index = 0; index < bytes.length; index += 256) {
      await this.#run(['send-keys', '-H', '-t', record.paneId, ...bytes.slice(index, index + 256)]);
    }
  }

  async resize(terminalId: string, cols: number, rows: number) {
    const record = await this.#record(terminalId);
    await this.#run(['resize-window', '-t', record.windowId, '-x', String(cols), '-y', String(rows)]);
  }

  async close(terminalId: string) {
    const records = await this.#records();
    const record = records.find((candidate) => candidate.terminalId === terminalId);
    if (!record) return;
    await this.#run(['kill-window', '-t', record.windowId], {}, [0, 1]);
    this.#recordsByPane.delete(record.paneId);
    this.#recordsByWindow.delete(record.windowId);
  }

  subscribe(listener: (event: TerminalBackendEvent) => void) {
    this.#listeners.add(listener);
    return () => this.#listeners.delete(listener);
  }

  dispose() {
    if (this.#disposed) return;
    this.#disposed = true;
    this.#listeners.clear();
    this.#controlClient?.close();
    this.#controlClient = undefined;
  }

  async #ensureControlClient() {
    if (this.#disposed || this.#controlClient) return;
    if (this.#controlOpening) return await this.#controlOpening;
    this.#controlOpening = (async () => {
      await this.#ensureSession(process.env['HOME'] ?? process.cwd());
      await this.#records();
      this.#controlClient = await this.#controlFactory({
        executable: this.#executable,
        args: [...this.#baseArgs(), '-C', 'attach-session', '-f', 'pause-after=1', '-t', SESSION_NAME],
        env: commandEnvironment(this.#env),
        handlers: {
          output: (paneId, data) => {
            const record = this.#recordsByPane.get(paneId);
            if (record) this.#emit({ terminalId: record.terminalId, type: 'output', data });
          },
          pause: (paneId) => {
            if (this.#manuallyPausedPanes.has(paneId)) return;
            void this.#run(['refresh-client', '-A', `${paneId}:continue`], {}, [0, 1]);
          },
          windowClosed: (windowId) => {
            const record = this.#recordsByWindow.get(windowId);
            if (!record) return;
            this.#recordsByWindow.delete(windowId);
            this.#recordsByPane.delete(record.paneId);
            this.#emit({ terminalId: record.terminalId, type: 'exit' });
          },
          boundary: () => this.#eventSequence,
          exited: () => this.#restartControlClient(),
          error: () => this.#restartControlClient(),
        },
      });
    })().finally(() => {
      this.#controlOpening = undefined;
    });
    await this.#controlOpening;
  }

  #restartControlClient() {
    this.#controlClient = undefined;
    if (this.#disposed || this.#listeners.size === 0) return;
    setTimeout(() => void this.#ensureControlClient().catch(() => undefined), 100);
  }

  #emit(event: UnsequencedTerminalBackendEvent) {
    const sequenced = { ...event, backendSequence: ++this.#eventSequence } as TerminalBackendEvent;
    for (const listener of this.#listeners) listener(sequenced);
  }

  async #controlCommand(args: string[]) {
    return await this.#controlCommandLine(args.map(shellQuote).join(' '));
  }

  async #controlCommandLine(command: string) {
    const client = this.#controlClient;
    if (!client) throw new Error('tmux control client is unavailable.');
    return await client.command(command);
  }

  async #record(terminalId: string) {
    const record = (await this.#records()).find((candidate) => candidate.terminalId === terminalId);
    if (!record) throw new Error(`Terminal is unavailable: ${terminalId}`);
    return record;
  }

  async #records() {
    await this.list();
    return [...this.#recordsByPane.values()];
  }

  #index(records: TmuxRecord[]) {
    this.#recordsByPane.clear();
    this.#recordsByWindow.clear();
    for (const record of records) {
      this.#recordsByPane.set(record.paneId, record);
      this.#recordsByWindow.set(record.windowId, record);
    }
  }

  async #ensureSession(cwd: string) {
    const ready = this.#sessionQueue.then(() => this.#ensureSessionOnce(cwd));
    this.#sessionQueue = ready.catch(() => undefined);
    await ready;
  }

  async #ensureSessionOnce(cwd: string) {
    const result = await this.#run(['has-session', '-t', SESSION_NAME], { cwd }, [0, 1]);
    if (result.code === 0) return;
    await this.#run(
      [
        'new-session',
        '-d',
        '-s',
        SESSION_NAME,
        '-n',
        '_weave_boot',
        '-c',
        cwd,
      ],
      { cwd },
      [0],
    );
  }

  async #ensureConfig() {
    this.#configReady ??= (async () => {
      await mkdir(dirname(this.#configPath), { recursive: true, mode: 0o700 });
      const defaultTerminal = await resolveDefaultTerminal(this.#env);
      await writeText(this.#configPath, buildConfig(defaultTerminal), { mode: 0o600 });
      await chmod(this.#configPath, 0o600).catch(() => undefined);
    })();
    await this.#configReady;
  }

  #baseArgs() {
    return ['-f', this.#configPath, '-S', this.#socketPath];
  }

  async #run(
    args: string[],
    options: { cwd?: string; env?: Record<string, string> } = {},
    acceptedCodes = [0],
  ): Promise<CommandResult> {
    await this.#ensureConfig();
    const env = { ...commandEnvironment(this.#env), ...options.env };
    let result: CommandResult;
    try {
      result = this.#runner
        ? await this.#runner([...this.#baseArgs(), ...args], { ...options, env })
        : await this.#runCommand(args, { ...options, env });
    } catch (cause) {
      if (isFsError(cause, 'ENOENT')) throw new Error(TMUX_REQUIRED);
      throw cause;
    }
    if (!acceptedCodes.includes(result.code)) {
      throw new Error(result.stderr || result.stdout || `tmux ${args[0] ?? 'command'} failed.`);
    }
    return result;
  }

  async #runCommand(args: string[], options: { cwd?: string; env: Record<string, string> }) {
    const output = await runProcess(this.#executable, {
      args: [...this.#baseArgs(), ...args],
      cwd: options.cwd,
      env: options.env,
      stdout: 'pipe',
      stderr: 'pipe',
    });
    return {
      code: output.code,
      stdout: decoder.decode(output.stdout),
      stderr: decoder.decode(output.stderr).trim(),
    };
  }
}
